### PR TITLE
Dezvoltare autocomplete landing directions

### PR DESCRIPTION
**Pull request by Sorelul**
-Autocomplete cu Google Maps API (Places API)
-Landing page varianta 2, culorile hartilor, fara glob
-Buton/link directii pe POI
-Camp nou optional detalii adresa (necesita implementare ulterioara de BE)
-Fix api key google

### CODE REVIEW

**Comment by 03b8** [comment]
6. Address autocomplete is not implemented in the community admin interface. Not sure what was part of the requirements though (@Tinux-18?)

**Comment by Tinux-18** [comment]
> 6. Address autocomplete is not implemented in the community admin interface. Not sure what was part of the requirements though (@Tinux-18?)

It was not.

**Comment by 03b8** [comment]
7. The link to Google Maps directions sets the address as source, not as destination.

**Comment by 03b8** [comment]
Voi face deployment aşa deocamdată, dar ar trebui să mai facem următoarele modificări:
1. reintrodus linkurile din footer (privacy-policy, terms-and-conditions, contact) :warning:
2. îndepărtat geojsonurile nefolosite
3. îndepărtat codul vechi comentat

**Comment by 03b8** [comment]
Se pare că au rămas ceva dependencies neutilizate care ar trebui curăţate şi ele:
image

**Pull request merged**
